// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Chris Collins <chris@hitorro.com>

/*
 * ACE PILOT - Atari Falcon030 port.
 *
 * Port of the Amiga version (main.c in geekychris/amiga_games, kept as
 * main.c.amiga): game.c, engine3d.c, models.c, render.c and sound.c are
 * unmodified (sound.h points ptplayer at the Paula emulation) and draw
 * on the Falcon port layer's true colour screen (../falcon_port/fgfx).
 * The MOD (Strauss's Blue Danube, generated by gen_mod.py) and the sound
 * effects play on the C ptplayer (../st_port/ptplayer) on the Paula
 * emulation (Falcon DMA sound).
 *
 * An 8 MHz STE manages about 2 frames per second of this game (about
 * 200 lines a frame and 16 32 bit-multiply-heavy enemy aiming searches
 * per game step), so it is a Falcon port: the 68030 multiplies in one
 * instruction and a chunky screen makes lines cheap.
 *
 * main.c's state machine runs at 50 Hz (as on the Amiga: one game step
 * per 50 Hz frame), up to 6 steps per displayed frame (the Falcon draws
 * about 10 a second); the view is redrawn in full once per frame.
 *
 * Controls: cursor keys / WASD or joystick 1 fly, Space / Alt / fire
 * shoot, Q / E throttle; on the title P toggles the display mode, F1 one
 * player, F2 two players (player 2 on joystick 0, the mouse port), fire
 * starts; Esc returns to the title, Esc there quits.  With Hatari
 * --natfeats on, events and symbol addresses are logged ("ACEP ..."
 * lines).
 */
#include <osbind.h>
#include <stdio.h>
#include <string.h>
#include "fgfx.h"
#include "st_ikbd.h"
#include "bridge_client.h"
#include "engine3d.h"
#include "game.h"
#include "render.h"
#include "input.h"
#include "sound.h"
#include "natfeats.h"

#define FRCLOCK (*(volatile long *)0x466)
#define TICK_HZ 50

void input_init(void);
void input_exit(void);

/* MOD data */
static UBYTE *mod_data = NULL;
static ULONG  mod_size = 0;
static WORD   music_playing = 0;

/* Game world */
static GameWorld world;

/* Authoritative top-level game state.
 * world.state covers PLAYING/DYING/GAMEOVER during gameplay; game_state
 * adds the STATE_TITLE overlay. */
static WORD game_state = STATE_TITLE;
static WORD mode_press = 0;

/* Palette: designed for both classic green and color modes */
static UWORD palette[16] = {
    0x000,  /*  0: black (background) */
    0xFFF,  /*  1: white (text, crosshair, player bullets) */
    0x0F0,  /*  2: bright green (classic near) */
    0x0EE,  /*  3: cyan (blimps) */
    0x0A0,  /*  4: green (classic medium / trees) */
    0x060,  /*  5: dark green (classic far / grid) */
    0xA70,  /*  6: brown/tan (ground buildings) */
    0x888,  /*  7: grey (text, divider) */
    0xF00,  /*  8: red (enemies, enemy bullets) */
    0xF80,  /*  9: orange (explosions) */
    0xFF0,  /* 10: yellow (HUD score) */
    0x800,  /* 11: dark red (far enemies) */
    0x04F,  /* 12: blue */
    0x040,  /* 13: dim green (classic very far / stars) */
    0xFA0,  /* 14: bright orange (close explosions) */
    0xFE0,  /* 15: bright yellow (prompts) */
};

/* MOD loading (GEMDOS; main.c used AmigaDOS: "DH2:Dev/blue_danube.mod") */
static UBYTE *load_file_to_chip(const char *path, ULONG *out_size)
{
    long fh = Fopen(path, 0), len;
    UBYTE *buf;
    if (fh < 0) return NULL;
    len = Fseek(0, (short)fh, 2);
    Fseek(0, (short)fh, 0);
    buf = len > 0 ? (UBYTE *)Malloc(len) : NULL;
    if (buf && Fread((short)fh, len, buf) != len) {
        Mfree(buf);
        buf = NULL;
    }
    Fclose((short)fh);
    if (buf) *out_size = (ULONG)len;
    return buf;
}

static void log_line(const char *fmt, long a, long b, long c, long d)
{
    char buf[128];
    strcpy(buf, "ACEP ");
    snprintf(buf + 5, sizeof(buf) - 6, fmt, a, b, c, d);
    strcat(buf, "\n");
    nf_print(buf);
}

/* one 50 Hz step of main.c's loop, without the drawing; 0 to quit */
static int game_step(void)
{
    UWORD inp1, inp2;

    /* Read input */
    inp1 = input_read_p1();
    inp2 = input_read_p2();

    if (inp1 & INPUT_ESC) {
        if (game_state == STATE_TITLE) {
            return 0;
        } else {
            game_state = STATE_TITLE;
        }
    }

    switch (game_state) {
    case STATE_TITLE:
        /* Toggle display mode */
        if ((inp1 & INPUT_MODE) && !mode_press) {
            g_tune.display_mode = 1 - g_tune.display_mode;
            mode_press = 1;
        }
        if (!(inp1 & INPUT_MODE)) mode_press = 0;

        /* Player count selection */
        if (inp1 & INPUT_TWO_P) g_tune.num_players = 2;
        if (inp1 & INPUT_START) g_tune.num_players = 1;

        /* Start game */
        if (inp1 & INPUT_FIRE) {
            game_init(&world);
            game_state = STATE_PLAYING;
        }
        break;

    case STATE_PLAYING:
    case STATE_DYING:
    case STATE_GAMEOVER:
        /* Update game */
        game_update(&world, inp1, inp2);

        /* Check for game over -> title transition */
        if (world.state == STATE_GAMEOVER && world.state_timer <= 0) {
            if (inp1 & INPUT_FIRE) {
                game_state = STATE_TITLE;
                break;
            }
        }
        break;
    }
    return 1;
}

/* main.c's rendering for the current state, into the back buffer */
static void game_draw(void)
{
    struct RastPort *rp = fgfx_back();

    if (game_state == STATE_TITLE) {
        render_title(rp);
        return;
    }
    if (g_tune.num_players >= 2) {
        /* Split screen */
        Viewport vp_top  = { 0, 0, SCREEN_W, SCREEN_H / 2 - 1 };
        Viewport vp_bot  = { 0, SCREEN_H / 2 + 1, SCREEN_W, SCREEN_H / 2 - 1 };
        render_scene(rp, &world, 0, &vp_top);
        render_hud(rp, &world, 0, &vp_top);
        render_scene(rp, &world, 1, &vp_bot);
        render_hud(rp, &world, 1, &vp_bot);
        render_divider(rp);
    } else {
        /* Single player full screen */
        Viewport vp_full = { 0, 0, SCREEN_W, SCREEN_H };
        render_scene(rp, &world, 0, &vp_full);
        render_hud(rp, &world, 0, &vp_full);
    }

    /* Game over overlay */
    if (world.state == STATE_GAMEOVER) {
        render_gameover(rp, &world);
    }
}

int main(void)
{
    long old_ssp, last_vbl, frames = 0;
    int running = 1, last_state = -1, last_wave = -1;
    long last_score = -1;

    nf_init();
    old_ssp = Super(0L);

    /* Init engine */
    engine3d_init();

    if (fgfx_init()) {
        Super((void *)old_ssp);
        Cconws("Ace Pilot needs a Falcon030 (16 bit true colour)\r\n");
        return 1;
    }
    {
        int i;
        for (i = 0; i < 16; i++)
            fgfx_set_rgb(i, ((palette[i] >> 8) & 15) * 17, ((palette[i] >> 4) & 15) * 17,
                         (palette[i] & 15) * 17);
    }

    /* Build sound effects */
    sound_init();

    /* ptplayer on the Paula emulation, for the effects and the music */
    paula_set_rate(6258);
    mt_install_cia(CUSTOM_BASE, NULL, 1);  /* PAL */
    if (mt_sound_ok() != 0)
        log_line("no DMA sound - continuing without sound", 0, 0, 0, 0);

    /* Load MOD music */
    mod_data = load_file_to_chip("BLUE_DAN.MOD", &mod_size);
    if (mod_data) {
        mt_init(CUSTOM_BASE, mod_data, NULL, 0);
        mt_MusicChannels = 2;
        mt_Enable = 1;
        music_playing = 1;
    } else {
        log_line("Could not load blue_danube.mod - no music", 0, 0, 0, 0);
    }
    input_init();

    log_line("START music=%ld", (long)music_playing, 0, 0, 0);
    log_line("SYMBOL world 0x%06lx", (long)&world, 0, 0, 0);
    log_line("SYMBOL players 0x%06lx", (long)world.players, 0, 0, 0);
    log_line("SYMBOL g_tune 0x%06lx", (long)&g_tune, 0, 0, 0);
    log_line("SYMBOL game_state 0x%06lx", (long)&game_state, 0, 0, 0);
    log_line("SYMBOL frame_sync 0x%06lx", (long)fgfx_swap, 0, 0, 0);

    const int vbl_hz = fgfx_height() == 240 ? 60 : 50;   /* VGA / RGB */
    long tick_acc = 0;
    last_vbl = FRCLOCK;
    while (running) {
        /* the steps due at TICK_HZ since the last frame (at most 6) */
        long now = FRCLOCK;
        int steps;
        tick_acc += (now - last_vbl) * TICK_HZ;
        last_vbl = now;
        steps = (int)(tick_acc / vbl_hz);
        tick_acc -= (long)steps * vbl_hz;
        if (steps > 6) { steps = 6; tick_acc = 0; }

        while (steps-- > 0 && running)
            running = game_step();

        {
            int st = game_state == STATE_TITLE ? STATE_TITLE : world.state;
            if (st != last_state || world.wave != last_wave) {
                static const char *n[] = { "TITLE", "PLAYING", "DYING", "GAMEOVER" };
                log_line("STATE %s wave=%ld players=%ld lives=%ld", (long)n[st & 3],
                         (long)world.wave, (long)g_tune.num_players,
                         (long)world.players[0].lives);
                last_state = st;
                last_wave = world.wave;
            }
        }
        if (world.players[0].score != last_score) {
            if (game_state != STATE_TITLE)
                log_line("SCORE %ld", (long)world.players[0].score, 0, 0, 0);
            last_score = world.players[0].score;
        }

        game_draw();
        fgfx_swap();
        frames++;
        if (frames % 100 == 0) {
            static long perf_vbl;
            long t = FRCLOCK;
            if (perf_vbl)
                log_line("PERF frames=100 vbls=%ld (%ld Hz) state=%ld", t - perf_vbl, vbl_hz,
                         game_state, 0);
            perf_vbl = t;
        }
    }

    log_line("EXIT frames=%ld score=%ld", frames, (long)world.players[0].score, 0, 0);
    if (music_playing)
        mt_end(CUSTOM_BASE);
    mt_remove_cia(CUSTOM_BASE);
    sound_cleanup();
    input_exit();
    fgfx_exit();
    Super((void *)old_ssp);
    return 0;
}
