# Nova Defense - Atari ST port
#   make CROSS=~/computers/atari-cc/opt/cross-mint/bin/m68k-atari-mintelf-
#   make run
NAME = NOVA
SRCS = main_st.c game.c draw.c st_input.c st_sound.c
include ../st_port/port.mk
