# Uranus Lander - Atari ST port
#   make CROSS=~/computers/atari-cc/opt/cross-mint/bin/m68k-atari-mintelf-
#   make run      # Hatari (ST, PAL EmuTOS) + agent API, build/ as C:, autostart
NAME = URANUS
SRCS = main_st.c game.c draw.c st_input.c st_sound.c
include ../st_port/port.mk
