# Frank the Frog - Atari ST port
#   make CROSS=~/computers/atari-cc/opt/cross-mint/bin/m68k-atari-mintelf-
#   make run
NAME = FROG
SRCS = main_st.c frank.c lanes.c playfield.c score.c st_sound.c st_modplay.c
include ../st_port/port.mk
