/*
 * STAKATTACK - Atari STE port.
 *
 * Port of the Amiga version (main.c in geekychris/amiga_games, kept as
 * main.c.amiga): game.c and draw.c run on the shared ST layer in
 * ../st_port.  The sound effects and the MOD loader below are copied
 * from main.c verbatim; the MOD (Korobeiniki, generated by
 * generate_mod.py) plays through the C ptplayer on the Paula emulation
 * (STE DMA sound).
 *
 * Drawing: the field (grid + locked cells) is the scenery layer, redrawn
 * only when the field changes; the falling piece, ghost, next box, HUD
 * and overlays are drawn every frame through the HUD layer, which only
 * renders what changed (draw.c's text and cells are cached operations).
 * Game logic runs once per 50 Hz VBL like the Amiga main loop.
 *
 * Controls: cursor keys / WASD or joystick to move, up / W to rotate,
 * down / S soft drop, Space / fire hard drop (start on the title), Alt /
 * Return start, P pause, Esc quits.  With Hatari --natfeats on, events
 * and symbol addresses are logged ("STAK ..." lines).
 */
#include <osbind.h>
#include <stdio.h>
#include <string.h>
#include <exec/memory.h>
#include <proto/dos.h>
#include "ptplayer.h"
#include "game.h"
#include "draw.h"
#include "input.h"
#include "natfeats.h"
#include "paula.h"

#define FRCLOCK (*(volatile long *)0x466)
#define CUSTOM_BASE ((void *)0xDFF000)	/* ignored by the C ptplayer */

extern const UWORD palette[NUM_COLORS];

static UBYTE *mod_data = NULL;
static ULONG mod_size = 0;
static BOOL music_playing = FALSE;
static BYTE *sfx_drop_data = NULL;
static BYTE *sfx_clear_data = NULL;
static BYTE *sfx_lock_data = NULL;
static BYTE *sfx_move_data = NULL;

#define SFX_DROP_LEN  256
#define SFX_CLEAR_LEN 512
#define SFX_LOCK_LEN  128
#define SFX_MOVE_LEN  64

static SfxStructure sfx_drop_sfx;
static SfxStructure sfx_clear_sfx;
static SfxStructure sfx_lock_sfx;
static SfxStructure sfx_move_sfx;

/* Game state */
static GameState gs;

/* ---- Sound Effects ---- */

static ULONG sfx_rng_state = 0x12345678;

static ULONG sfx_rng(void)
{
    sfx_rng_state = sfx_rng_state * 1103515245 + 12345;
    return (sfx_rng_state >> 16) & 0x7FFF;
}

static void build_sfx(void)
{
    int i;

    /* Drop: deep thud */
    sfx_drop_data = (BYTE *)AllocMem(SFX_DROP_LEN, MEMF_CHIP | MEMF_CLEAR);
    if (sfx_drop_data) {
        for (i = 0; i < SFX_DROP_LEN; i++) {
            int env = 127 - (i * 127 / SFX_DROP_LEN);
            int wave = (i % 16 < 8) ? 80 : -80;
            sfx_drop_data[i] = (BYTE)((wave * env) / 127);
        }
        sfx_drop_sfx.sfx_ptr = (APTR)sfx_drop_data;
        sfx_drop_sfx.sfx_len = SFX_DROP_LEN / 2;
        sfx_drop_sfx.sfx_per = 400;
        sfx_drop_sfx.sfx_vol = 64;
        sfx_drop_sfx.sfx_cha = -1;
        sfx_drop_sfx.sfx_pri = 10;
    }

    /* Clear: rising sparkle */
    sfx_clear_data = (BYTE *)AllocMem(SFX_CLEAR_LEN, MEMF_CHIP | MEMF_CLEAR);
    if (sfx_clear_data) {
        for (i = 0; i < SFX_CLEAR_LEN; i++) {
            int env = 127 - (i * 100 / SFX_CLEAR_LEN);
            int freq = 4 + (i * 12 / SFX_CLEAR_LEN);
            int wave = (i % freq < freq / 2) ? 70 : -70;
            int noise = (int)(sfx_rng() & 0x1F) - 16;
            sfx_clear_data[i] = (BYTE)(((wave + noise) * env) / 127);
        }
        sfx_clear_sfx.sfx_ptr = (APTR)sfx_clear_data;
        sfx_clear_sfx.sfx_len = SFX_CLEAR_LEN / 2;
        sfx_clear_sfx.sfx_per = 200;
        sfx_clear_sfx.sfx_vol = 55;
        sfx_clear_sfx.sfx_cha = -1;
        sfx_clear_sfx.sfx_pri = 20;
    }

    /* Lock: short click */
    sfx_lock_data = (BYTE *)AllocMem(SFX_LOCK_LEN, MEMF_CHIP | MEMF_CLEAR);
    if (sfx_lock_data) {
        for (i = 0; i < SFX_LOCK_LEN; i++) {
            int env = (i < 8) ? 127 : 127 - ((i - 8) * 127 / (SFX_LOCK_LEN - 8));
            int wave = (i % 6 < 3) ? 60 : -60;
            sfx_lock_data[i] = (BYTE)((wave * env) / 127);
        }
        sfx_lock_sfx.sfx_ptr = (APTR)sfx_lock_data;
        sfx_lock_sfx.sfx_len = SFX_LOCK_LEN / 2;
        sfx_lock_sfx.sfx_per = 300;
        sfx_lock_sfx.sfx_vol = 45;
        sfx_lock_sfx.sfx_cha = -1;
        sfx_lock_sfx.sfx_pri = 5;
    }

    /* Move: tiny tick */
    sfx_move_data = (BYTE *)AllocMem(SFX_MOVE_LEN, MEMF_CHIP | MEMF_CLEAR);
    if (sfx_move_data) {
        for (i = 0; i < SFX_MOVE_LEN; i++) {
            int env = (i < 4) ? 127 : 127 - ((i - 4) * 127 / (SFX_MOVE_LEN - 4));
            sfx_move_data[i] = (BYTE)((((i % 4 < 2) ? 40 : -40) * env) / 127);
        }
        sfx_move_sfx.sfx_ptr = (APTR)sfx_move_data;
        sfx_move_sfx.sfx_len = SFX_MOVE_LEN / 2;
        sfx_move_sfx.sfx_per = 200;
        sfx_move_sfx.sfx_vol = 30;
        sfx_move_sfx.sfx_cha = -1;
        sfx_move_sfx.sfx_pri = 2;
    }
}

static void free_sfx(void)
{
    if (sfx_drop_data) FreeMem(sfx_drop_data, SFX_DROP_LEN);
    if (sfx_clear_data) FreeMem(sfx_clear_data, SFX_CLEAR_LEN);
    if (sfx_lock_data) FreeMem(sfx_lock_data, SFX_LOCK_LEN);
    if (sfx_move_data) FreeMem(sfx_move_data, SFX_MOVE_LEN);
}

/* ---- MOD file loading ---- */

static UBYTE *load_file_to_chip(const char *path, ULONG *out_size)
{
    BPTR fh;
    UBYTE *buf = NULL;
    LONG len;

    fh = Open((CONST_STRPTR)path, MODE_OLDFILE);
    if (!fh) return NULL;

    Seek(fh, 0, OFFSET_END);
    len = Seek(fh, 0, OFFSET_BEGINNING);
    if (len <= 0) { Close(fh); return NULL; }

    buf = (UBYTE *)AllocMem(len, MEMF_CHIP);
    if (!buf) { Close(fh); return NULL; }

    if (Read(fh, buf, len) != len) {
        FreeMem(buf, len);
        Close(fh);
        return NULL;
    }

    Close(fh);
    *out_size = (ULONG)len;
    return buf;
}

/* ---- Display Setup ---- */


static void log_line(const char *fmt, long a, long b, long c, long d)
{
    char buf[128];
    strcpy(buf, "STAK ");
    snprintf(buf + 5, sizeof(buf) - 6, fmt, a, b, c, d);
    strcat(buf, "\n");
    nf_print(buf);
}

static const char *state_names[] = { "TITLE", "PLAYING", "PAUSED", "GAMEOVER" };

/* scenery: the field when playing, empty on the title */
static ULONG scenery_key = 0xffffffffUL;

static ULONG field_key(void)
{
    ULONG k = gs.state == STATE_TITLE ? 0x7177 : 1;
    const ULONG *p = (const ULONG *)gs.field;
    int i;
    if (gs.state == STATE_TITLE)
        return k;
    for (i = 0; i < (int)(sizeof(gs.field) / 4); i++)
        k = (k << 3 | k >> 29) ^ p[i];
    return k;
}

static void draw_frame(void)
{
    struct RastPort *hud = gfx_hud();
    ULONG key = field_key();

    if (key != scenery_key) {
        struct RastPort *bg = gfx_bg();
        SetRast(bg, 0);
        if (gs.state != STATE_TITLE)
            draw_field(bg, &gs);
        gfx_bg_to_screens();
        scenery_key = key;
    }

    /* main.c's drawing, minus what is in the scenery */
    switch (gs.state) {
    case STATE_TITLE:
        draw_title(hud);
        break;
    case STATE_PLAYING:
    case STATE_PAUSED:
        draw_ghost_piece(hud, &gs);
        draw_current_piece(hud, &gs);
        draw_next_piece(hud, &gs);
        draw_hud(hud, &gs);
        if (gs.clear_timer > 0)
            draw_line_clear_flash(hud, &gs);
        if (gs.state == STATE_PAUSED)
            draw_paused(hud);
        break;
    case STATE_GAMEOVER:
        draw_hud(hud, &gs);
        draw_gameover(hud, &gs);
        break;
    }
    gfx_hud_commit();
    gfx_restore_back();
}

int main(void)
{
    long old_ssp, last_vbl, frames = 0;
    int running = 1, last_state = -1;
    ULONG last_score = 0xffffffffUL;

    nf_init();
    old_ssp = Super(0L);

    if (!gfx_init(palette, 16)) {
        Super((void *)old_ssp);
        Cconws("Not enough memory\r\n");
        return 1;
    }
    gfx_set_frame_vbls(1);
    input_init();
    build_sfx();

    /* Load MOD music (PROGDIR:stakattack.mod -> STAKATTA.MOD) */
    paula_set_rate(6258);
    mod_data = load_file_to_chip("PROGDIR:stakattack.mod", &mod_size);
    mt_install_cia(CUSTOM_BASE, NULL, 1); /* PAL */
    if (mod_data) {
        mt_init(CUSTOM_BASE, mod_data, NULL, 0);
        mt_MusicChannels = 2;
        mt_mastervol(CUSTOM_BASE, 40);
        mt_Enable = 1;
        music_playing = TRUE;
    }

    game_init(&gs);

    log_line("START music=%ld sound=%s", (long)music_playing,
             (long)(mt_sound_ok() == 0 ? "dma" : "none"), 0, 0);
    log_line("SYMBOL gs 0x%06lx", (long)&gs, 0, 0, 0);
    log_line("SYMBOL field 0x%06lx", (long)&gs.field, 0, 0, 0);
    log_line("SYMBOL current 0x%06lx", (long)&gs.current, 0, 0, 0);
    log_line("SYMBOL state 0x%06lx", (long)&gs.state, 0, 0, 0);
    log_line("SYMBOL score 0x%06lx", (long)&gs.score, 0, 0, 0);
    log_line("SYMBOL frame_sync 0x%06lx", (long)gfx_swap, 0, 0, 0);

    last_vbl = FRCLOCK;
    while (running) {
        long now = FRCLOCK;
        int steps = (int)(now - last_vbl);
        last_vbl = now;
        if (steps < 1) steps = 1;
        if (steps > 3) steps = 3;

        /* main.c's per-frame input and update, once per 50 Hz VBL */
        while (steps-- > 0) {
            UWORD input = input_read();
            int game_input;
            if (input & INPUT_ESC) running = 0;
            {
                /* Edge detection for buttons that need press-not-hold */
                UWORD edges = input_edge(input);

                /* Map input to game input */
                game_input = 0;
                if (input & INPUT_LEFT)   game_input |= GINPUT_LEFT;
                if (input & INPUT_RIGHT)  game_input |= GINPUT_RIGHT;
                if (input & INPUT_DOWN)   game_input |= GINPUT_DOWN;

                /* Rotate on edge only (up arrow, W) */
                if (edges & INPUT_UP)     game_input |= GINPUT_ROTATE;

                /* Space and fire: hard drop during gameplay, start otherwise */
                if (edges & INPUT_FIRE) {
                    if (gs.state == STATE_PLAYING)
                        game_input |= GINPUT_DROP;
                    else
                        game_input |= GINPUT_START;
                }

                /* Start/pause on edge only (enter, alt, joystick fire, P) */
                if (edges & (INPUT_START | INPUT_PAUSE))
                    game_input |= GINPUT_START;
            }

            /* Update game */
            game_update(&gs, game_input);

            /* Play SFX based on game events */
            if (gs.just_locked && sfx_lock_data)
                mt_playfx(CUSTOM_BASE, &sfx_lock_sfx);
            if (gs.just_cleared && sfx_clear_data)
                mt_playfx(CUSTOM_BASE, &sfx_clear_sfx);
            if (gs.just_dropped && sfx_drop_data)
                mt_playfx(CUSTOM_BASE, &sfx_drop_sfx);
        }

        if (gs.state != last_state) {
            log_line("STATE %s score=%ld level=%ld lines=%ld", (long)state_names[gs.state & 3],
                     (long)gs.score, gs.level, gs.lines);
            last_state = gs.state;
        }
        if (gs.score != last_score) {
            log_line("SCORE %ld level=%ld lines=%ld", (long)gs.score, gs.level, gs.lines, 0);
            last_score = gs.score;
        }

        draw_frame();
        gfx_swap();
        frames++;
        if (frames % 100 == 0) {
            static long perf_vbl;
            long t = FRCLOCK;
            if (perf_vbl)
                log_line("PERF frames=100 vbls=%ld state=%ld", t - perf_vbl, gs.state, 0, 0);
            perf_vbl = t;
        }
    }

    log_line("EXIT frames=%ld score=%ld", frames, (long)gs.score, 0, 0);
    if (music_playing)
        mt_end(CUSTOM_BASE);
    mt_remove_cia(CUSTOM_BASE);
    free_sfx();
    if (mod_data) FreeMem(mod_data, mod_size);
    input_cleanup();
    gfx_exit();
    Super((void *)old_ssp);
    return 0;
}
