# Rock Blaster - Atari STE port
#   make CROSS=~/computers/atari-cc/opt/cross-mint/bin/m68k-atari-mintelf-
#   make run
NAME     = ROCKBLST
SRCS     = main_st.c game.c draw.c st_input.c
ST_EXTRA = paula ptplayer
MACHINE  = ste
include ../st_port/port.mk
